# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  pull_request:
  workflow_call:
    outputs:
      semver:
        description: "The full SemVer 2.0 version of this build, e.g. '2026.6.0-alpha.1234' (note: no 'v'-prefix)"
        value: ${{ jobs.build.outputs.semver }}
      file_version:
        description: "The file info version, e.g. '2026.6.0.1234'"
        value: ${{ jobs.build.outputs.file_version }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.set-version.outputs.semver }}
      file_version: ${{ steps.set-version.outputs.file-version }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - id: set-version
        name: Set version to output
        shell: bash
        run: |
          TAG=${{ github.ref_name }}
          if [[ "${{ github.ref }}" != refs/tags/* ]]; then
            TAG="v0.0.99.${{ github.run_number }}"
          fi
          SEMVER="${TAG#v}"
          FILE_VERSION=$(echo "$TAG" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          FILE_VERSION="$FILE_VERSION.${{ github.run_number }}"

          echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"
          echo "file-version=$FILE_VERSION" >> "$GITHUB_OUTPUT"

          echo $SEMVER
          echo $FILE_VERSION

      - name: Set connector version
        run: |
          python patch_version.py ${{steps.set-version.outputs.semver}}

      - name: Create SketchUp package
        run: zip -q -r sketchup.zip vendor speckle_connector_3/ speckle_connector_3.rb

      - name: ⬆️ Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: output-${{steps.set-version.outputs.semver}}
          path: sketchup.zip
          retention-days: 1
          if-no-files-found: error
          compression-level: 0 # no compression
