# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and deploy

on:
  push:
    branches: ["dui3/alpha", deploy/*] # Continuous delivery on every long-lived branch
    tags: ["3.*"] # Manual delivery on every 3.x tag

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-installers:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔫 Trigger Build Installers
        uses: ALEEF02/workflow-dispatch@v3.0.0
        with:
          workflow: Build Sketchup
          repo: specklesystems/connector-installers
          token: ${{ secrets.CONNECTORS_GH_TOKEN }}
          inputs: '{ "run_id": "${{ github.run_id }}", "semver": "${{ needs.build.outputs.semver }}", "file_version": "${{ needs.build.outputs.file_version }}" }'
          ref: sketchup-installer-fix
          wait-for-completion: true
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 10m
          display-workflow-run-url: true
          display-workflow-run-url-interval: 10s
