# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and deploy

on:
  push:
    branches: ["main", "installer-test/**"]
    tags: ["v3.*.*"] # Manual delivery on every 3.x tag

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-installers:
    runs-on: ubuntu-latest
    needs: build
    env:
      IS_TAG_BUILD: ${{ github.ref_type == 'tag' }}
    steps:
      - name: 🔫 Trigger Build Installer(s)
        uses: the-actions-org/workflow-dispatch@v4.0.0
        with:
          workflow: Build Installers
          repo: specklesystems/connector-installers
          token: ${{ secrets.CONNECTORS_GH_TOKEN }}
          inputs: '{
            "run_id": "${{ github.run_id }}",
            "semver": "${{ needs.build.outputs.semver }}",
            "file_version": "${{ needs.build.outputs.file_version }}",
            "repo": "${{ github.repository }}",
            "is_public_release": ${{ env.IS_TAG_BUILD }}
            }'
          ref: jrm/experiment-similar-ci
          wait-for-completion: true
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 10m
          display-workflow-run-url: true
          display-workflow-run-url-interval: 10s
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: output-*
