query {
  activeUser {
    id
    email
    name
    bio
    company
    avatar
    verified
    profiles
    role
    streams {
      totalCount
    }
    commits(limit: 1) {
      totalCount
      items {
        id
        createdAt
      }
    }
  }
}
